version: '3.2'

services:

  grafana:
    image: grafana/grafana:7.3.1
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    ports:
      - '3000:3000'
  renderer:
    image: grafana/grafana-image-renderer:3.3.0
    ports:
      - 8081
  reporter:
    image: grafana-reporter:0.2
    command: "-ip grafana:3000"
    environment:
      MAX_WORKERS: 5
    ports:
      - "8686:8686"
#http://localhost:8686/api/v5/report/oohJ9Axnz